version: '3'

services:
  db:
    image: mysql:8.0.32
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    image: wordpress:6.1.1-php8.0-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_AUTH_KEY=5f6ede1b94d25a2294e29eeba929a8c80a5ac0fb
      - WORDPRESS_SECURE_KEY=5f6ede1b94d25a2294e29eeba929a8c80a5ac0fb
      - WORDPRESS_LOGGED_IN_KEY=5f6ede1b94d25a2294e29eeba929a8c80a5ac0fb
      - WORDPRESS_NONCE_KEY=5f6ede1b94d25a2294e29eeba929a8c80a5ac0fb
      - WORDPRESS_SECURE_AUTH_SALT=5f6ede1b94d25a2294e29eeba929a8c80a5ac0fb
      - WORDPRESS_LOGGED_IN_SALT=5f6ede1b94d25a2294e29eeba929a8c80a5ac0fb
      - WORDPRESS_NONCE_SALT=5f6ede1b94d25a2294e29eeba929a8c80a5ac0fb
      - WORDPRESS_CONFIG_EXTRA=
          define('WP_CACHE', false);
          define('ENVIRONMENT', 'local');
          if (!defined('WP_HOME')) {
            define('WP_HOME', 'http://wordpress-local.com');
            define('WP_SITEURL', WP_HOME);
          }
    volumes:
      - wordpress:/var/www/html
      - ./themes:/var/www/html/wp-content/themes:delegated
      - ./plugins:/var/www/html/wp-content/plugins
      - ./uploads:/var/www/html/wp-content/uploads
      - ./logs:/var/www/html/wp-content/logs
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./config/error-logging.ini:/usr/local/etc/php/conf.d/error-logging.ini
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.23.3-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - app-network

volumes:
  wordpress:
  dbdata:

networks:
  app-network:
    driver: bridge
